# global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ["alertmanager:7070"]

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'ml_app' 
    static_configs:
    - targets: ["host.docker.internal:6062"]
    
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets :  ["cadvisor:8080"]





    